config/routes.rb
MKTW::Application.routes.draw do
 
  root :to => 'pages#home'
  
  match '/dashboard',     :to => 'pages#dashboard'
  
  resources :tweets, :only => [:index]
  resources :users, :only => [:index]
  resources :companies, :only => [:index, :show]
  resources :parsed_raw_tweets, :only => [:index, :show]
  
  

end

app/models/parsed_raw_tweet.rb
class ParsedRawTweet < ActiveRecord::Base

end

app/controllers/parsed_raw_tweets_controller.rb
class ParsedRawTweetsController < ApplicationController
  
  # GET /parsed_raw_tweets
  # GET /parsed_raw_tweets.json
  def index
    @title = "Positive Sentiment | Parsed Raw Tweets"
    @keywords = ""
    
    @parsed_raw_tweets = ParsedRawTweet.paginate(:per_page => 20, :page => params[:page])
    
    if params[:parse_status]
      @parsed_raw_tweets = @parsed_raw_tweets.where(:parse_status => params[:parse_status])
    end
   
    if params[:tweet_guid]
      @parsed_raw_tweets = @parsed_raw_tweets.where(:tweet_guid => params[:tweet_guid])
    end 
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parsed_raw_tweets }
    end
  end

  # GET /parsed_raw_tweets/1
  # GET /parsed_raw_tweets/1.json
  def show    
    
    @parsed_raw_tweet = ParsedRawTweet.find(params[:id])
    
    @title = "Positive Sentiment | Parsed Raw Tweet ID: "+params[:id]
    @keywords = ""
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parsed_raw_tweet }
    end
  end
  
end

app/helpers/parsed_raw_tweets_helper.rb
module ParsedRawTweetsHelper
end

app/views/parsed_raw_tweets/index.html.erb
<h2>Parsed Raw Tweets</h2>
<p>List of parsed raw tweets</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>GUID</th>
      <th>Parse Status</th>
      <th>Created At</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <% @parsed_raw_tweets.each do |parsed_raw_tweet| %>
    <tr>
      <td><%= link_to parsed_raw_tweet.id, parsed_raw_tweet_path(parsed_raw_tweet) %></td>
      <td><%= parsed_raw_tweet.tweet_guid %></td>
      <td><%= parsed_raw_tweet.parse_status %></td>
      <td><%= parsed_raw_tweet.created_at %></td>
      <td><%= parsed_raw_tweet.updated_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @parsed_raw_tweets %>

<p>---</p>
<p><%= debug params %></p>

app/views/parsed_raw_tweets/show.html.erb
<h3>Parsed Raw Tweet: <%= @parsed_raw_tweet.id %></h3>
<dl class="dl-horizontal">
  <dt>Tweet GUID</dt>
  <dd><%= @parsed_raw_tweet.tweet_guid %></dd>
  <dt>Parse Status</dt>
  <dd><%= @parsed_raw_tweet.parse_status %></dd>
  <dt>Created At</dt>
  <dd><%= @parsed_raw_tweet.created_at %></dd>
  <dt>Updated At</dt>
  <dd><%= @parsed_raw_tweet.updated_at %></dd>
  <dt>Raw</st>
  <dd><%= @parsed_raw_tweet.raw %></dd>
</dl>

<p>---</p>
<p><%= debug params %></p>