config/routes.rb
MKTW::Application.routes.draw do
 
  root :to => 'pages#home'
  
  match '/dashboard',     :to => 'pages#dashboard'
  
  resources :tweets, :only => [:index]
  resources :users, :only => [:index]
  resources :companies, :only => [:index, :show]
  resources :parsed_raw_tweets, :only => [:index, :show]
  
  

end

app/views/pages/_companies_summary.html.erb
<h3>Companies</h3>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
<% @company_names.each do |company_name| %>
        <tr>
          <td><%= company_name.company_name %></td>
        </tr>
<% end %>
 </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

app/views/pages/_company_keywords_summary.html.erb
<h3>Company Keywords</h3>
<% @company_keyword_count.each do |count_row| %>
  <p> Record Count: <%= count_row["company_keyword_count"] %></p>
<% end %>

app/views/pages/_new_raw_tweets_summary.html.erb
<h3>New Raw Tweets</h3>
<% @new_raw_tweet_count.each do |count_row| %>
  <p> Record Count: <%= count_row["nrt_count"] %></p>
<% end %>

app/views/pages/_parsed_raw_tweets_summary.html.erb
<h3>Parsed Raw Tweets</h3>
<% @parsed_raw_tweet_count.each do |count_row| %>
  <p> Record Count: <%= count_row["prt_count"] %></p>
<% end %>
<h4>Breakdown by parse status</h4>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Status</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody>
      <% @parse_status_count.each do |count_row| %>
        <tr>
          <td><%= count_row.parse_status %></td>
          <td><%= count_row.parse_status_count %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td>Total</td>
          <% @parsed_raw_tweet_count.each do |count_row| %>
          <td><%= count_row["prt_count"] %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

app/views/pages/_tags_summary.html.erb
<h3>Tags</h3>
<% @tag_count.each do |count_row| %>
  <p> Record Count: <%= count_row["tag_count"] %></p>
<% end %>
<h4>Top tag count</h4>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Tag</th>
          <th>Sentiment</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody>
      <% @top_tags_count.each do |count_row| %>
        <tr>
          <td><%= count_row.tag_name %></td>
          <td><%= count_row.sentiment %></td>
          <td><%= count_row.tag_count %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td colspan="2" >Total</td>
          <% @tag_count.each do |count_row| %>
          <td><%= count_row["tag_count"] %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>
<h4>Top tag count today</h4>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Tag</th>
          <th>Sentiment</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody>
      <% @top_tags_count_today.each do |count_row| %>
        <tr>
          <td><%= count_row.tag_name %></td>
          <td><%= count_row.sentiment %></td>
          <td><%= count_row.tag_count %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td colspan="2" >Total</td>
          <td>...</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>


app/views/pages/_tweets_summary.html.erb
<h3 class="menu">Tweets</h3>
<p>Record Count: <%= @tweets.count %></p>
<p>Breakdown by sentiment</p>
<ul>
<% @tweet_sentiment_count.each do |count_row| %>
<li><%= count_row.sentiment %>: <%= count_row.sentiment_count %></li>
<% end %>
<li>Total: <%= @tweets.count %></p>
</ul>
<p>Breakdown by day</p>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Date</th>
          <th>Hour</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody>
      <% @tweet_daily_count.each do |count_row| %>
        <tr>
          <td><%= count_row.tweet_by_day %></td>
          <td><%= count_row.tweet_by_hour %></td>
          <td><%= count_row.tweet_daily_count %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td colspan="2" >Total</td>
          <td><%= @tweets.count %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

app/views/pages/_users_summary.html.erb
<h3>Users</h3>
<% @user_count.each do |count_row| %>
  <p> Record Count: <%= count_row["user_count"] %></p>
<% end %>

app/views/pages/dashboard.html.erb
<h2 class="menu">Dashboard</h2>
<p><%= page_loaded %></p>
<%= render "new_raw_tweets_summary" %>
<%= render "parsed_raw_tweets_summary" %>
<%= render "companies_summary" %>
<%= render "company_keywords_summary" %>
<%= render "users_summary" %>
<%= render "tags_summary" %>
<%= render "tweets_summary" %>

app/views/pages/home.html.erb
<h2 class="menu">Dashboard</h2>
<p><%= page_loaded %></p>

<h3>Companies</h3>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
<% @company_names.each do |company_name| %>
        <tr>
          <td><%= link_to company_name.company_name, company_path(:id => company_name.id)  %></td>
        </tr>
<% end %>
 </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

<h3>Raw Tweets</h3>
<p>Total New Raw Tweets: <%= @new_raw_tweet_count %></p>
<p>Total Parsed Raw Tweets: <%= @parsed_raw_tweet_count %></p>

<h4>Breakdown by parse status</h4>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Status</th>
          <th>Count</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @parse_status_count.each do |count_row| %>
        <tr>
          <td><%= count_row.parse_status %></td>
          <td><%= count_row.parse_status_count %></td>
          <td><%= link_to "Show", parsed_raw_tweets_path(:parse_status => count_row.parse_status)  %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td>Total</td>
          <td><%= @parsed_raw_tweet_count %></td>
          <td><%= link_to "Show", parsed_raw_tweets_path %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

<h3>Tweets</h3>
<p>Total: <%= @tweet_count %></p>

<h4>Breakdown by sentiment</h4>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Sentiment</th>
          <th>Count</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @tweet_sentiment_count.each do |count_row| %>
        <tr>
          <td><%= count_row.sentiment %></td>
          <td><%= count_row.sentiment_count %></td>
          <td><%= link_to "Show", tweets_path(:sentiment => count_row.sentiment)  %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td>Total</td>
          <td><%= @tweet_count %></td>
          <td><%= link_to "Show", parsed_raw_tweets_path %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

<h4>Breakdown by day</h4>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Date</th>
          <th>Count</th>
        </tr>
      </thead>
      <tbody>
      <% @tweet_daily_count.each do |count_row| %>
        <tr>
          <td><%= count_row.tweet_by_day %></td>
          <td><%= count_row.tweet_daily_count %></td>
        </tr>
      <% end %>
        <tr class="total">
          <td>Total</td>
          <td><%= @tweet_count %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="span8">
  </div>
</div>

<h3>Users</h3>
<p>Total: <%= @user_count %></p>

<h3>Tags</h3>
<p>Total: <%= @tag_count %></p>

<h3>Company Keywords</h3>
<p>Total: <%= @company_keyword_count %></p>

<h3>Company Prices</h3>
<p>Total: <%= @company_price_count %></p>

<p>---</p>
<p><%= debug params %></p>