config/routes.rb
MKTW::Application.routes.draw do
 
  root :to => 'pages#home'
  
  match '/dashboard',     :to => 'pages#dashboard'
  
  resources :tweets, :only => [:index]
  resources :users, :only => [:index]
  resources :companies, :only => [:index, :show]
  resources :parsed_raw_tweets, :only => [:index, :show]
  
  

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Positive Sentiment</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Dashboard", "/dashboard" %></li>
            <li><%= link_to "Tweets", tweets_url %></li>
            <li><%= link_to "Users", users_url %></li>
            
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="language" content="English">
  <meta name="keywords" content="<%= keywords %>">
  
  <link href="/favicon.png" rel="shortcut icon"> 
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon">
  <link href="/apple-touch-icon-72x72.png" sizes="72x72" rel="apple-touch-icon">
  <link href="/apple-touch-icon-114x114.png" sizes="114x114" rel="apple-touch-icon">
  
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "custom", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <!-- Load the Google Charts AJAX API-->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    

</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row full-width">
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>